rule_sets:
  google_accessibility_developer_tools:
    name: 'Google Accessibility Developer Tools'
    runner:
      filepath: 'vendor/access-lint/bin/auditor.js'
      additional_arguments:
  html_codesniffer:
    name: 'HTML CodeSniffer'
    runner:
      filepath: 'vendor/squizlabs/PhantomJS/HTMLCS_Run.js'
      additional_arguments:
        0: 'WCAG2AA'
