rule_sets:
  google_accessibility_developer_tools:
    name: 'Google Accessibility Developer Tools'
    runner_command: 'phantomjs vendor/access-lint/bin/auditor.js'
  html_code_sniffer:
    name: 'HTML CodeSniffer'
    filepath: 
